<a href="https://colab.research.google.com/github/Sharma-Pranav/Tensorflow_Training/blob/master/Composing_Custom_Layers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import tensorflow as tf
tf.enable_eager_execution()

In [0]:
class mydenselayer(tf.keras.layers.Layer):
  def __init__(self, num_outputs):
    super(mydenselayer, self).__init__()
    self.num_outputs = num_outputs
    
  def build(self, input_shape):
    self.kernel = self.add_variable('kernel', shape = [int(input_shape[-1]), self.num_outputs])
    
  def call(self, input):
    return tf.matmul(input, self.kernel)

In [5]:
layer = mydenselayer(10)
print(layer(tf.zeros([10, 5])))
print(layer.trainable_variables)

tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]], shape=(10, 10), dtype=float32)
[<tf.Variable 'mydenselayer_1/kernel:0' shape=(5, 10) dtype=float32, numpy=
array([[-0.10234058,  0.19065177, -0.3972822 , -0.16360667,  0.2588014 ,
         0.11439031, -0.18830368,  0.3601789 , -0.22636089,  0.16712838],
       [-0.12792617,  0.46502906,  0.5213695 ,  0.4248454 ,  0.39140886,
         0.43017596, -0.5797009 ,  0.53141326,  0.54871804,  0.13790905],
       [ 0.03565967, -0.06212211,  0.27753377, -0.22062308, -0.19969624,
        -0.01216716, -0.51593304, -0.43941617,  0.01887339, -0.42862132],
       [ 0.1612007 , -0.56092614, -0.24041581,  0.51730055, -0.31343138,
         0.11122721,  0.0514158 ,  0

In [0]:
class ResnetIdentityBlock(tf.keras.Model):
  def __init__(self, kernel_size, filters):
    super(ResnetIdentityBlock, self).__init__(name = '')
    filters1, filters2, filters3 = filters
    
    self.conv2a = tf.keras.layers.Conv2D(filters1, (1, 1))
    self.bn2a = tf.keras.layers.BatchNormalization()

    self.conv2b = tf.keras.layers.Conv2D(filters2, kernel_size, padding='same')
    self.bn2b = tf.keras.layers.BatchNormalization()

    self.conv2c = tf.keras.layers.Conv2D(filters3, (1, 1))
    self.bn2c = tf.keras.layers.BatchNormalization()
  def call(self, input_tensor, training = False):
    x = self.conv2a(input_tensor)
    x = self.bn2a(x, training = training)
    x = tf.nn.relu(x)
    
    x = self.conv2b(x)
    x = self.bn2b(x, training = training)
    x = tf.nn.relu(x)
    
    x = self.conv2c(x)
    x = self.bn2c(x, training = training)
    x += input_tensor
    return tf.nn.relu(x)

In [11]:
block = ResnetIdentityBlock(1, [1, 2, 3])
print(block(tf.zeros([1, 2, 3, 3])))
print([x.name for x in block.trainable_variables])

Instructions for updating:
Colocations handled automatically by placer.
tf.Tensor(
[[[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]]], shape=(1, 2, 3, 3), dtype=float32)
['resnet_identity_block_1/conv2d_1/kernel:0', 'resnet_identity_block_1/conv2d_1/bias:0', 'resnet_identity_block_1/batch_normalization_v1_1/gamma:0', 'resnet_identity_block_1/batch_normalization_v1_1/beta:0', 'resnet_identity_block_1/conv2d_2/kernel:0', 'resnet_identity_block_1/conv2d_2/bias:0', 'resnet_identity_block_1/batch_normalization_v1_2/gamma:0', 'resnet_identity_block_1/batch_normalization_v1_2/beta:0', 'resnet_identity_block_1/conv2d_3/kernel:0', 'resnet_identity_block_1/conv2d_3/bias:0', 'resnet_identity_block_1/batch_normalization_v1_3/gamma:0', 'resnet_identity_block_1/batch_normalization_v1_3/beta:0']
